direction: right

client: Client

client -> docker_compose.api_gateway: request

docker_compose: docker-compose {
  api_gateway: API Gateway
  user: User
  video: Video
  analytics: Analytics

  kafka: Kafka
  user_db: User DB
  video_db: Video DB
  analytics_db: Analytics DB

  api_gateway -> user: TCP
  api_gateway -> video: TCP
  api_gateway -> analytics: TCP

  video -> kafka: produce
  kafka -> analytics: consume

  user -> user_db
  video -> video_db
  analytics -> analytics_db
}
